#ifndef HIFUHTTPSERVER_GLOBAL_H
#define HIFUHTTPSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HIFUHTTPSERVER_LIBRARY)
#  define HIFUHTTPSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HIFUHTTPSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HIFUHTTPSERVER_GLOBAL_H
