#ifndef HIFUCONNECTION_GLOBAL_H
#define HIFUCONNECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HIFUCONNECTION_LIBRARY)
#  define HIFUCONNECTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HIFUCONNECTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HIFUCONNECTION_GLOBAL_H
