#ifndef IMAGECAPTURE_GLOBAL_H
#define IMAGECAPTURE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGECAPTURE_LIBRARY)
#  define IMAGECAPTURESHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGECAPTURESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGECAPTURE_GLOBAL_H
