#ifndef PLANSCENE3D_GLOBAL_H
#define PLANSCENE3D_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLANSCENE3D_LIBRARY)
#  define PLANSCENE3DSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLANSCENE3DSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLANSCENE3D_GLOBAL_H
