#ifndef REALTIMESCENE_GLOBAL_H
#define REALTIMESCENE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REALTIMESCENE_LIBRARY)
#  define REALTIMESCENESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REALTIMESCENESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REALTIMESCENE_GLOBAL_H
