#ifndef PHASECONTROLLER_GLOBAL_H
#define PHASECONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHASECONTROLLER_LIBRARY)
#  define PHASECONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHASECONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHASECONTROLLER_GLOBAL_H
