#ifndef SERVICEBUFFER_GLOBAL_H
#define SERVICEBUFFER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVICEBUFFER_LIBRARY)
#  define SERVICEBUFFERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVICEBUFFERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVICEBUFFER_GLOBAL_H
