#ifndef HIFUNAVIGATION_GLOBAL_H
#define HIFUNAVIGATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HIFUNAVIGATION_LIBRARY)
#  define HIFUNAVIGATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HIFUNAVIGATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HIFUNAVIGATION_GLOBAL_H
