#ifndef IMAGEGRABBER_GLOBAL_H
#define IMAGEGRABBER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEGRABBER_LIBRARY)
#  define IMAGEGRABBERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEGRABBERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEGRABBER_GLOBAL_H
