#ifndef HIFUALGOPROCESSOR_GLOBAL_H
#define HIFUALGOPROCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HIFUALGOPROCESSOR_LIBRARY)
#  define HIFUALGOPROCESSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HIFUALGOPROCESSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HIFUALGOPROCESSOR_GLOBAL_H
